package eu.yeger.refunk.exception

class OverflowException : FunctionException("An overflow has occurred during the evaluation of a function")
